// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CurrentDagschotelController from "./current_dagschotel_controller"
application.register("current-dagschotel", CurrentDagschotelController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import OrderController from "./order_controller"
application.register("order", OrderController)

import ProductsController from "./products_controller"
application.register("products", ProductsController)

import ScannerController from "./scanner_controller"
application.register("scanner", ScannerController)

import StockController from "./stock_controller"
application.register("stock", StockController)

import UserController from "./user_controller"
application.register("user", UserController)
