name: Ruby

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install ImageMagick
      run: sudo apt-get install -y imagemagick


    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - run: RAILS_ENV=test bundle exec rake db:create
    - run: RAILS_ENV=test bundle exec rake db:schema:load
    - run: bundle exec rake
      env:
        COVERALLS_REPO_TOKEN : ${{ secrets.COVERALLS_REPO_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Lint with rubocop
        env:
          RAILS_ENV: "test"
        run: |
          bundle exec rubocop -c  .rubocop.yml
